### ISSUE TITLE
(feat) Client Hints prototype for adaptive-loading

### ISSUE THREAD

**Issue by addyosmani** [GoogleChromeLabs/adaptive-loading#38]
> Client hints are a set of opt-in HTTP request headers that give us insight into these aspects of the user’s device and the network they’re connected to. By tapping into this information server side, we can change how we deliver content based on device and/or network conditions. This can help us to create more inclusive user experiences. 

Examples of signals they provide include:

* Device-Memory
* Network hints (ECT)
* DPR
* Viewport Width

I would like for us to work on a Node/Express prototype using Client Hints to demonstrate how to apply adaptive-loading on the server. As most of the work we've done in the repo to date is about adapting how we fetch resources or code _client-side_, it would be valuable to highlight how decisions can be made before you send many of your payloads over the network in the first place. 

One caveat with Client hints is that they don’t kick in on the navigation request the first time a user visits your site and are of course, only available in a limited number of browsers. However, if you persist hints with Accept-CH-Lifetime, this information will be available on the navigation request. We can document any limitations in a README as we work through this.

In terms of approach, I'm comfortable with us initially experimenting with the image serving use-case (using Client Hints to send down the most appropriate image based on ECT, DPR, memory). I feel this will be focused enough problem that we can work out just how much we want to explore the Service Worker path etc. before we start looking at adaptive code-serving from the server.

For the initial implementation, I would like for us to not factor in the Save Data header. We can explore some dedicated examples around it at a later date.

**Reference:**
- https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/client-hints/
- https://httpwg.org/http-extensions/client-hints.html
- https://www.keycdn.com/blog/client-hints

**Comment by anton-karlovskiy** [comment]
@addyosmani
I've just found a very interesting issue.

It looks like the network ECT emulator in Chrome Dev Tool does not have an effect on Client Hints.

Even if I throttle it to 3g (actually 4g), the 4g image shows. I thought that there might be a bug in our server side logic.
But I made sure there was no error in the server side logic by testing serveral laptops in different network condition (not emulated condition but real condition).

Testing scenario:
On the real 4g browser it persists showing 4g image regardless of emulated ECT (e.g. 3g, 2g)
On the real 3g browser it persists showing 3g image regardless of emulated ECT (e.g. 4g, 2g)
https://adaptive-loading.firebaseapp.com/node-network-aware-loading/ -> tested URL

More interesting is that when I emulate the network ECT on local node server, it was reflected on Client Hints.
I confirmed by testing on local as well.

I wonder if this has something to do with Accept-CH-Lifetime. FYI: I have not implemented this property.

**Comment by anton-karlovskiy** [comment]
@addyosmani 
Client Hints are not attached to header in the request for IFrame.
![no-client-hints](https://user-images.githubusercontent.com/49653735/64933710-0df9c700-d84f-11e9-8f20-765269791e5f.PNG)
![with-client-hints](https://user-images.githubusercontent.com/49653735/64933712-0e925d80-d84f-11e9-92fe-f7b67a62a57f.PNG)
