### ISSUE TITLE
[Demo] Save Data 

### ISSUE THREAD

**Issue by addyosmani** [GoogleChromeLabs/adaptive-loading#51]
**2 Demos:**

- Explore a Save Data Hook + demo
- Explore a Save Data Client Hint demo

**Reference:**
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/save-data/

cc @anton-karlovskiy 

Demo outline:

Rather than re-using one of the existing demos, I would like us to try replicating something that already exists for this one. How about we re-create the Twitter Timeline (with fake data, e.g content from Unsplash) using react-window and duplicate the Data Saver effect Twitter uses for their official feature: 

https://www.wikihow.com/Turn-on-the-Data-Saver-on-Twitter

![image](https://user-images.githubusercontent.com/110953/65900664-6068d680-e36b-11e9-8814-4bfcfe950d52.png)

![image](https://user-images.githubusercontent.com/110953/65900639-51822400-e36b-11e9-84cc-d157abf47ba6.png)

In terms of implementation:

1. When a user loads the demo, they will be presented with a Timeline of made-up tweets. Some of these will contain images. We will not need to use any Twitter API for these. Style-wise, I would like the cards to be close-enough to what Twitter actually uses that you can tell "Oh, that's a tweet"
2. When a user enables Data Saver mode (Save Data is a browser feature, so they need to do this in their browser), we will serve a low-fi version of the images (LQIP). When a user clicks on the image in Data Saver mode, it will load the original. I would like you to test how Twitter's actual Data Saver feature works so you understand how this works right now.
3. If a user disables Data Saver mode, then the normal images are loaded. 
4. Let's initially focus on the client-side version of this demo then talk about the server version using Client Hints.
5. Let's implement an in-demo toggle for Data Saver to let the user "simulate" what happens when Data Saver is toggled. 

Keep in mind, for now, we will only be focusing on adaptive resource-loading, but not adaptive code loading (just trying to switch how images are loaded for this demo).

**Comment by anton-karlovskiy** [comment]
@addyosmani 
Working on this project, I found something interesting in using Save-Data client hint.
I was testing on Google Chrome browser and even thought I attached Save-Data client hint to request headers, I couldn't capture Save-Data header.
```
const myHeaders = new Headers({
  'Save-Data': 'on',
  'Data-Saver': 'on'
});

fetch('/network-memory-considerate-model', {
  headers: myHeaders
})
.then(response => response.json())
.then(result => {
  setExperienceType(result.experienceType);
});
```
![no save-data   data-saver in chrome](https://user-images.githubusercontent.com/49653735/66227118-30139600-e6e5-11e9-868e-4822168923ed.png)

**Comment by addyosmani** [comment]
> So I'm going to use Data-Saver request header for now to implement this project.

I'll take blame for not catching that it was going to be difficult to debug Save Data on desktop now that the [Chrome extension](https://www.ghacks.net/2019/04/24/google-deprecates-chrome-data-saver-extension-for-the-desktop/) for Data Saver has been deprecated (leaving Data Saver/Lite Mode for Android as the main way to use the feature and test it).

Do you have access to a BrowserStack account? It's possible to test and debug Data Saver from a real Android device. You need to go to Settings > Lite Mode and enable it. Here's a test using https://client-hints-demo.appspot.com/http-equiv.html (Accept-CH and Accept-CH-Lifetime meta http-equiv response headers) where you can see Save Data coming through as expected:

![image](https://user-images.githubusercontent.com/110953/66238751-0dfe2180-e6ad-11e9-84b5-a7dec037120d.png)

**Comment by anton-karlovskiy** [comment]
@addyosmani 
I tested using BrowserStack Samsung Galaxy 10.
With the Lite Mode setting enabled, we can capture `save-data` request header on server side.
But with the Lite Mode setting disabled, we can't capture `save-data` request header on server side, even though we manually attached `Save-Data` header to the request.

**Comment by addyosmani** [comment]
Excellent. That is the behaviour I would expect. This feature should only ever work (be true) if Lite Mode is enabled.

**Comment by anton-karlovskiy** [comment]
@addyosmani 
## Glitch Source
* [Link to Glitch App](https://anton-karlovskiy-react-save-data-twitter.glitch.me/)
* [Link to Project on Glitch](https://glitch.com/~anton-karlovskiy-react-save-data-twitter/)

Please check the above Glitch application.
Actually both of Save-Data Client Hint based demo on server side as well as React hook based demo on client side are developed but on Glitch it's a bit difficult to run Node.js serving create-react-app project. So please try client side demo first.
I'll get it up and running on our Adaptive Loading firebase instance when landing on the PR.
A bit of refinement is left yet.

**Comment by anton-karlovskiy** [comment]
@addyosmani 
Glitch app is updated for load image feature which can be found in the center of image on lite mode.

**Comment by addyosmani** [comment]
Tested latest Glitch using the forced client-side manual testing and it
appears to be working great. I can't get it working with Lite Mode turned
on in Chrome for Android however. Is that coming?

**Comment by anton-karlovskiy** [comment]
@addyosmani 
For now, on Glitch, it's a bit difficult to get it working with Lite Mode turned on in Chrome for Android.
But the implementation is done. We can deploy it to Adaptive Loading firebase instance with functions.
Then we can test it.

**Comment by anton-karlovskiy** [comment]
@addyosmani 
I think Twitter applies adaptive loading to videos as well as images like `autoplay`.
We could also apply `autoplay` feature as we have the interface [here](https://github.com/anton-karlovskiy/adaptive-loading/blob/009a80f80fa83f0234d56f3ae2ac47b73f96c47e/react-twitter-save-data-loading/src/App.js#L78).
