### ISSUE TITLE
[Bug] Some hooks have the problem to cause a re-render for no good reason

### ISSUE THREAD

**Issue by anton-karlovskiy** [GoogleChromeLabs/adaptive-loading#55]
- device-class -- hook fixed
https://github.com/GoogleChromeLabs/adaptive-loading/blob/master/hooks/device-class/index.js
- hardware-concurrency -- hook fixed
https://github.com/GoogleChromeLabs/adaptive-loading/blob/master/hooks/hardware-concurrency/index.js
- memory -- hook fixed
https://github.com/GoogleChromeLabs/adaptive-loading/blob/master/hooks/memory/index.js

Above hooks cause re-rendering by useState inside useEffect for no good reason.

So I think we should:
- update above hooks -- done
- update Unit Tests for above hooks -- done
- update demos using above hooks and deploy to Adaptive Loading firebase instance -- done
- update override toggle logic in cna-memory-considerate-animation using exported setState method from updated memory hook -- reject

**Comment by addyosmani** [comment]
Interesting. Do we have a test case where we can see re-rendering being caused by one of the existing hooks above? 

The latest React Profiler and Component Profiler don't appear to be working with the memory deploy. That said, if you could talk me through the issues you're seeing, happy for us to consider spending time fixing these bugs.

**Comment by anton-karlovskiy** [comment]
@addyosmani 
Yes, this issue is not a serious one and not a blocker.
But with above hooks, the component should be re-rendered once to use the hook logic and we could avoid it. I think I made a mistake and not considered this point.

Let me try making a test case by adding a console log to show rendering times in both cases.
One case is re-rendering with the current hook.
The other case is just one render with the updated hook.

**Comment by anton-karlovskiy** [comment]
@addyosmani 
I tried to make a test case project. I added the console log to the component with the memory hook.

The one with re-rendering. We are supposed to see two times of console log in that component.
![console-rerendering](https://user-images.githubusercontent.com/49653735/66739427-4d7cf880-ee79-11e9-896e-ee8284bd5ca0.PNG)

The one with no re-rendering. We are supposed to see just one time of console log in that component.
![console-no-rerendering](https://user-images.githubusercontent.com/49653735/66739456-62598c00-ee79-11e9-8206-36ca3110c085.PNG)

**Comment by anton-karlovskiy** [comment]
@addyosmani 
I've just found that it's not supported to import hooks outside of `src/`.
I tried to import `useDeviceClass` hook from the main project hooks directory but failed with this.
![Capture](https://user-images.githubusercontent.com/49653735/67002107-d6976800-f0e3-11e9-9836-0b948a01fdd8.PNG)
https://stackoverflow.com/questions/44114436/the-create-react-app-imports-restriction-outside-of-src-directory

**Comment by addyosmani** [comment]
What's the workaround we are choosing here?

**Comment by anton-karlovskiy** [comment]
> What's the workaround we are choosing here?

I'm afraid I have not chosen workaround yet. Just copy and paste the hook inside the project.
According to some articles, they say we can disable it in the webpack then we might have to eject create-react-app.

**Comment by anton-karlovskiy** [comment]
@addyosmani 
I think we could use [react-app-rewired](https://github.com/timarney/react-app-rewired) to override webpack configuration.
The other day when I used this package, it's a bit painful.

**Comment by addyosmani** [comment]
I think for now copying and pasting is fine. We will probably want to shift eventually to relying on published npm packages, but we should wait until the Hooks are more final before doing so.

**Comment by anton-karlovskiy** [comment]
@addyosmani 
Yes, I investigated npm publish option too.
If we used npm, we wouldn't face this issue.

OK, I got your points.
