### ISSUE TITLE
[Demo] Network-aware code loading (eBay)

### ISSUE THREAD

**Issue by addyosmani** [GoogleChromeLabs/adaptive-loading#58]
eBay are experimenting with adaptive loading where, similar to some of our demos, they only load the code necessary for zooming into an image if a user is on a fast connection. There is a screenshot of what this looks like below. 

I would like for us to take [this page](https://www.ebay.com/itm/Nike-Flex-Run-2016-Mens-Runinng-Shoe-Crimson-Black-830369-601-sz-11/152669264255?var=452220570389&hash=item238bcc197f:m:m8JGGvA8IYbBZVTWARQvq5g) and re-implement a simplified version of it. e.g maybe we just implement what is in the viewport...but with better stars :)

![image](https://user-images.githubusercontent.com/110953/67132211-37b85c00-f208-11e9-8f74-a53cc6a6320f.png)

![image](https://user-images.githubusercontent.com/110953/67132187-27a07c80-f208-11e9-9681-25b74597ace7.png)

This would use the network-aware code-splitting pattern to decide whether or not to load the ability to zoom in on a product image. As this is a demo, I would like to see if we can use a heavier zooming component to stress just how much could be theoretically saved.

eBay's zooming looks like this on desktop:

![image](https://user-images.githubusercontent.com/110953/67132295-b3b2a400-f208-11e9-95d2-1820ed315cd9.png)

I would recommend trying eBay's page out on mobile and desktop (emulated) so you see how they currently function.

Example:
![T9888B - Speed at Scale_ Web Perf Tips   Tricks From The Trenches (11)](https://user-images.githubusercontent.com/110953/67132089-b82a8d00-f207-11e9-9144-9728d127da44.png)

References:
https://adaptive-loading.web.app/cra-network-aware-code-splitting/
https://adaptive-loading.web.app/react-shrine-network-aware-code-splitting/

@anton-karlovskiy fyi

**Comment by anton-karlovskiy** [comment]
@addyosmani 
Good news to me. I was hungry for projects :)

**Comment by anton-karlovskiy** [comment]
@addyosmani 
FYI: I tried eBay on 2g connection (used Chrome Dev Tools throttling) but it looks like the zooming feature is not disabled on low connection.

I think I have not correctly understand how much we should implement regarding `e.g maybe we just implement what is in the viewport` since the viewport is a bit long with scroll.
As well on desktop and mobile, the view look quite different.

On desktop we can implement magnifying feature but on mobile it does not look possible to use magnifying feature. So I think we we can implement pop-up dialog and pinch-to-zoom feature like eBay does currently.

**Comment by addyosmani** [comment]
Yeah, this behaviour is currently only an experiment they have not made available to everyone just yet. So what you see on their live site is a little different.

What you suggested sounds fine to me. By what is in the viewport, I mean, what you can see when you first open the page. Let's start prototyping and we can tweak as we go along?

**Comment by anton-karlovskiy** [comment]
@addyosmani 
> I would like to see if we can use a heavier zooming component to stress just how much could be theoretically saved.

FYI: We have used [react-magnifier](https://bundlephobia.com/result?p=react-magnifier@3.0.4) so I think we can use [react-image-magnifier](https://bundlephobia.com/result?p=react-image-magnify@2.7.4) which is heavier.

**Comment by addyosmani** [comment]
Looks perfect 👌

**Comment by anton-karlovskiy** [comment]
@addyosmani 
Not only [react-image-magnify](https://bundlephobia.com/result?p=react-image-magnify@2.7.4) but also [react-responsive-modal](https://github.com/pradel/react-responsive-modal) is used for heavy experience as eBay does.

Here you can check the current status of the project.
* [Link to Glitch App](https://https://anton-karlovskiy-network-aware-ebay.glitch.me/)
* [Link to Project on Glitch](https://glitch.com/~anton-karlovskiy-network-aware-ebay)

I also analyzed the chunk sizes.

Lite experience:

Heavy experience:
![Uploading magnific-product.PNG…]()

**Comment by addyosmani** [comment]
This looks really great so far, Anton. It's exactly what I had in mind!

I'm seeing larger bundle sizes on the live Glitch than locahost. Is this because we're serving React dev mode on Glitch but will be serving the production build on Firebase?

**Comment by anton-karlovskiy** [comment]
@addyosmani 
Yes, build version on localhost:5000 but React dev mode on Glitch.

**Comment by addyosmani** [comment]
Shall we move this to PR?

**Comment by anton-karlovskiy** [comment]
@addyosmani 
Yes, but a bit more work left. Today I'll create a PR.

**Comment by anton-karlovskiy** [comment]
@addyosmani 
Do you think it looks like eBay on desktop and mobile view?
Mobile view looks a bit different from the real eBay.
