### ISSUE TITLE
[WIP] Microsite

### ISSUE THREAD

**Issue by addyosmani** [GoogleChromeLabs/adaptive-loading#63]
Mock:
![image](https://user-images.githubusercontent.com/110953/67242601-b2e96000-f40a-11e9-8978-d4a8054c6569.png)

![image](https://user-images.githubusercontent.com/110953/67242730-f93ebf00-f40a-11e9-8191-aa40155c140c.png)

Theme inspiration: https://material.io/design/

Current icon (need to figure out what we're actually going to use):
https://www.iconfinder.com/icons/4272271/analytics_comparison_data_icon

- Implement in Next.js
- Let's have a page include a thumbnail gallery of all the demos. That is, a CSS Grid with a medium sized screenshot of each demo that you can click through to see the original. Each thumbnail cell/div should include the name of the demo in white text below the screenshot.
- Try to fill out pages with content from our existing docs/READMEs
- Performance-wise, it's perfectly OK for this to be mostly server-side rendered. There's very little that should require client side rendering here.
- This page will be hosted at the root of adaptive-loading.web.dev, treated like an index page.
- Let's leave placeholders for the images for now. I'll send images soon.
- We should try to limit work on this to under two days. The homepage and demos area may take time to implement, but the rest will be very much copying/pasting existing markdown content.

Wdyt?

**Comment by anton-karlovskiy** [comment]
@addyosmani 
I think I have understood the outline of this microsite.

As for the theming, shall we use [material-ui](https://material-ui.com/)?

**Comment by addyosmani** [comment]
I think as long as we can keep the performance of our landing page high, using Material UI sounds fine. The alternative might be looking at one of the smaller sized Material implementations. 

In my view, we mostly need a Material navigation bar (could be CSS if not opting for a drawer). The rest is pretty custom. I don't think we necessarily need to use cards or FAB buttons for this page. Picturing the links just being links :)

**Comment by anton-karlovskiy** [comment]
@addyosmani 
Yes, I got your points.
Using Material UI might be expensive on the performance.
I think we can just use Material components as many as required without installing the whole Material UI framework. Actually just with CSS, we could implement the feel and look.

**Comment by addyosmani** [comment]
👍👍👍

**Comment by addyosmani** [comment]
Nice! Good start :) Some quick notes:

* We might want to use SVG versions of the Material icons as we'll probably only need to pull in a few vs all of Material Icons font https://material.io/resources/icons/?style=baseline
* Image for the right-hand-side can be found here: [low-data-small.png.zip](https://github.com/GoogleChromeLabs/adaptive-loading/files/3791220/low-data-small.png.zip)
* Content-wise, it might make sense for us to include snippets from the Hooks [readme](https://github.com/GoogleChromeLabs/adaptive-loading/tree/master/hooks) so folks can easily see how to use them in the same place?

**Comment by anton-karlovskiy** [comment]
@addyosmani 

Thank you for your feedback. It's just the beginning of the project for now.
Yes, I remember the svg icon usage to improve the performance, which you taught me the other day.

**Comment by addyosmani** [comment]
Hey Anton. For the purposes of priorities next week, could we focus on #86 and #83 then come back to the microsite?

**Comment by anton-karlovskiy** [comment]
> s next week, c

Yes, I'll proceed that way.

**Comment by anton-karlovskiy** [comment]
> Hey Anton. For the purposes of priorities next week, could we focus on #86 and #83 then come back to the microsite?

Yes, I'll proceed that way.

**Comment by anton-karlovskiy** [comment]
@addyosmani 

Could you please give me a fav icon and the main icon highlighted in red?
Thanks.
![67242601-b2e96000-f40a-11e9-8978-d4a8054c6569](https://user-images.githubusercontent.com/49653735/68744995-d6b55580-0606-11ea-937d-21725c0cd81d.png)

**Comment by anton-karlovskiy** [comment]
@addyosmani 

In the material design, Roboto font is used. What kind of font shall we use?

**Comment by addyosmani** [comment]
Fonts: I think we can safely opt for Roboto as long as we are using a safe `font-display` default to minimize invisible text being shown. 

> Could you please send me a fav icon and the main icon highlighted in red?

yes, i'll dig that up right now.

**Comment by addyosmani** [comment]
An SVG version of the icon can be found below:

[iconfinder_comparison_data_analytics_4272271.svg.zip](https://github.com/GoogleChromeLabs/adaptive-loading/files/3847949/iconfinder_comparison_data_analytics_4272271.svg.zip)

Favicons for the page, generated with realfavicongenerator can also be found below:

[favicon_package_v0.16 (1).zip](https://github.com/GoogleChromeLabs/adaptive-loading/files/3847959/favicon_package_v0.16.1.zip)

**Comment by anton-karlovskiy** [comment]
@addyosmani 

https://anton-karlovskiy-adaptive-loading-microsite.glitch.me/demos
Currently our Microsite looks so.
TODOs on my side:
- optimize the demo images -> it's raw screenshots.
- fixing broken image links
I think the demo screen shots do not look pretty like the ones shown on the conference.
I wonder if we need some art to make them look pretty. Could you please ...? :)
Could you please give me some instructions like `Resources` nav button, `Search` button, `HIGHLIGHTS` on home and so on?

**Comment by anton-karlovskiy** [comment]
@addyosmani 

Roboto font is set across the website with `font-display` swap.

**Comment by anton-karlovskiy** [comment]
@addyosmani 

Next.js has some problem with css module importing.
They are working on it but not resolved yet.
So I just adopted the workaround for importing some css module.

Re:
https://github.com/zeit/next-plugins/issues/282
https://github.com/zeit/next.js/issues/5598#issuecomment-437619043
https://github.com/zeit/next.js/issues/5291
https://github.com/zeit/next.js/issues/5598#issuecomment-443319470
https://github.com/zeit/next.js/issues/5264#issuecomment-424000127

**Comment by anton-karlovskiy** [comment]
@addyosmani 

According to Lighthouse, Roboto font was one of the potential savings in order to improve the performance.
So we've ended up using Arial for now.
