### ISSUE TITLE
[Hooks] Save Data hook

### ISSUE THREAD

**Issue by addyosmani** [GoogleChromeLabs/adaptive-loading#64]
We implemented a demo using the Save Data API over in https://github.com/GoogleChromeLabs/adaptive-loading/issues/51. I think it would make sense to follow this up with a Hooks implementation for Save Data to make it easier for reuse.

We should probably also keep in mind the lessons learned from https://github.com/GoogleChromeLabs/adaptive-loading/issues/55.

cc @anton-karlovskiy

**Comment by anton-karlovskiy** [comment]
@addyosmani 
For this demo, we don't depend on React hooks, but on the Save Data API as Client Hint usage.
The React hook here is just for updating a certain state value like [this line](https://github.com/GoogleChromeLabs/adaptive-loading/blob/ab5e202f673c49745e514e0a84b945b58c6a996f/react-twitter-save-data-loading/src/App.js#L79).

**Comment by addyosmani** [comment]
I'm aware the Twitter demo uses Client Hints, but a React Hook using the client-side JavaScript API for Save Data still makes sense, right? It's very similar in nature to the other Hooks that don't rely on client hints.

**Comment by anton-karlovskiy** [comment]
@addyosmani 
In this demo, we have not used client-side Javascript API for Save Data.
On client side, we just manually change the resource path for the state value.

**Comment by addyosmani** [comment]
I am aware of this :) I'm not saying let's rewrite the Twitter app to use client-side Save Data, but rather, for consistency we should make sure a Hook exists for someone that would like to do this.

It's based on navigator.connection.saveData.

**Comment by anton-karlovskiy** [comment]
@addyosmani 

:) I have not used `navigator.connection.saveData` here. Then I'll implement the React hook with `navigator.connection.saveData` API.

**Comment by anton-karlovskiy** [comment]
@addyosmani 
I found the following from [MDN](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/saveData)
The NetworkInformation.saveData read-only property of the NetworkInformation interface returns true if the user has set a reduced data usage option on the user agent.

I'd like to confirm again that what we have to do is not to update the Twitter app but to implement the React hook with `navigator.connection.saveData`.

Looks like I missed something in https://github.com/GoogleChromeLabs/adaptive-loading/issues/51#event-2731689656.
That is, I have not developed the client side demo for `Explore a Save Data Hook + demo` but just the  server side demo for `Explore a Save Data Client Hint demo` with manual testing functionality.

**Comment by anton-karlovskiy** [comment]
Re:
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/save-data/

**Comment by addyosmani** [comment]
- Let's keep the current Twitter demo as is (no changes)
- Let's implement a React Hook that uses navigator.connection.saveData (for the hooks directory)
- Let's build a demo using the React Hook to show it being used (maybe it's a copy of the Twitter demo that uses the client-side Hook instead of Client Hints just for comparison)

Does that make sense?  :)

**Comment by anton-karlovskiy** [comment]
@addyosmani 
Yes, that's it I wanted to confirm.
Makes a lot of sense. :)

**Comment by anton-karlovskiy** [comment]
@addyosmani 
In this project, I think we can figure out the mobile and desktop detection by feature.
as mentioned on https://github.com/GoogleChromeLabs/adaptive-loading/pull/54#discussion_r336696444.

**Comment by addyosmani** [comment]
We can return to that feedback at a later date. It's okay to not consider the mobile check feedback for now.
