### ISSUE TITLE
[Demo] Dixie mechanical keyboard

### ISSUE THREAD

**Issue by addyosmani** [GoogleChromeLabs/adaptive-loading#68]
I think it would be useful for us to implement a slimmed down demo of a page really using `<model-viewer>` and show how we can fallback to an image if you are on a memory-constrained device 😄  

Dixie Mech is one such page and I think is simple enough that coming up with a reduced demo would not take us too long. 

Original: https://dixiemech.com/gmkdracula (we should link to the original lower down the page)

Demo to evolve: https://adaptive-loading.web.app/cra-memory-considerate-loading/ (we can keep this one and treat Dixie as another memory-considerate demo)

Notes: To view the model you need to wait a second for the animation then click on it to see the model-viewer. I'd say for a slimmed down demo, we could just show the model-viewer on page load without the animations. Focus on implementing just the top part of the page that's in view?

![image](https://user-images.githubusercontent.com/110953/67423103-7fccdb00-f588-11e9-9f54-05f50fdf463c.png)

3D `<model-viewer>` code (for licensing reasons, let's just use the below and not self-host):

```
<model-viewer src="https://ephektz.com/assets/dboard.glb" background-color="#2b2b2b" exposure="0.3" id="boardEl" ar="" camera-orbit="0deg 0deg auto" style="position: absolute; width: 100%; height: 80%; top: 10%; opacity: 1;"></model-viewer>
```

Static screenshot for fallback:

![image](https://user-images.githubusercontent.com/110953/67421780-07fdb100-f586-11e9-8015-0ee6aa5a11d9.png)

I will also try reaching out to see if they are okay with this usage.

cc @anton-karlovskiy

**Comment by anton-karlovskiy** [comment]
@addyosmani 
Yes I got it.

**Comment by addyosmani** [comment]
Could we start a PR for this demo? :)

**Comment by anton-karlovskiy** [comment]
> Could we start a PR for this demo? :)

Yes for sure. It's started. :)
