### ISSUE TITLE
[hooks] Memory hook feedback

### ISSUE THREAD

**Issue by addyosmani** [GoogleChromeLabs/adaptive-loading#69]
Our React Hooks currently return a number of different kinds of values:

* Network returns a `string` of 2g/3g/4g etc.
* Hardware concurrency returns an `integer` for the number of cores
* Memory returns a `boolean` of whether you are overloaded
* Battery returns a `float` value . (e.g 0.75)
* Device class returns a `string` for light/heavy

Of these values, memory stands out as a hook where we (project authors) are making a decision about what is overloaded. For all the other hooks, we just give developers the value and let them make a decision themselves.

For consistency, we should rewrite the memory hook to just provide a value from `navigator.deviceMemory` and optionally provide access to performance memory data, but assume the deviceMemory value is the main thing developers are after here. 

cc @anton-karlovskiy

**Comment by anton-karlovskiy** [comment]
@addyosmani 
It makes sense.

1. updating memory hook with its Unit Test
2. updating memory demo projects
3. updating hooks/README
4. deployment again

**Comment by addyosmani** [comment]
That would be great. Thank you!
