### ISSUE TITLE
[hooks] Return values feedback

### ISSUE THREAD

**Issue by addyosmani** [GoogleChromeLabs/adaptive-loading#70]
After reviewing our current hooks, I noticed that there were opportunities to simplify how they are used after being imported. 

Currently, we export [unit-test specific values](https://github.com/GoogleChromeLabs/adaptive-loading/blob/master/hooks/memory/index.js#L94) in addition to the main values developers care about. I think such information (just for tests) can be duplicated as needed as constant values in those tests, but we can avoid exporting them if it makes it easier for developers to use the hooks.

A few examples below:

Current:
```js
import React from 'react';

import { useHardwareConcurrency } from './hardware-concurrency';

const MyComponent = () => {
  const { hardwareConcurrency: { numberOfLogicalProcessors } } = useHardwareConcurrency();
  return (
    <div>
      { numberOfLogicalProcessors <= 4 ? <img src='...' /> : <video src='...' /> }
    </div>
  );
};
```

Expected:

```js
import React from 'react';

import { useHardwareConcurrency } from './hardware-concurrency';

const MyComponent = () => {
  const { numberOfLogicalProcessors }  = useHardwareConcurrency();
  return (
    <div>
      { numberOfLogicalProcessors <= 4 ? <img src='...' /> : <video src='...' /> }
    </div>
  );
};
```

Current:

```js
import React from 'react';

import { useMemoryStatus } from './memory';

const MyComponent = () => {
  const { memoryStatus: { overLoaded } } = useMemoryStatus();
  return (
    <div>
      { overLoaded ? <img src='...' /> : <video src='...' /> }
    </div>
  );
};
```

Expected:

```js
import React from 'react';

import { useMemoryStatus } from './memory';

const MyComponent = () => {
  const { overLoaded } = useMemoryStatus();
  return (
    <div>
      { overLoaded ? <img src='...' /> : <video src='...' /> }
    </div>
  );
};
```

Current:

```js
import React from 'react';

import { useBatteryStatus } from './battery';

const MyComponent = () => {
  const { batteryStatus: { level } } = useBatteryStatus();
  return (
    <div>
      { level > 0.75 ? <video src='...' /> : <img src='...' /> }
    </div>
  );
};
```

Expected:

```js
import React from 'react';

import { useBatteryStatus } from './battery';

const MyComponent = () => {
  const { level } = useBatteryStatus();
  return (
    <div>
      { level > 0.75 ? <video src='...' /> : <img src='...' /> }
    </div>
  );
};
```

Would it be possible for us to simplify the output of the hooks to something like the above?

cc @anton-karlovskiy

**Comment by anton-karlovskiy** [comment]
@addyosmani 
Yes, sounds like a good idea.

**Comment by anton-karlovskiy** [comment]
@addyosmani 

FYI: When you review PRs, could you please review this https://github.com/GoogleChromeLabs/adaptive-loading/pull/71 firstly among PRs since it also includes a new hook, which should be refactored as well?

**Comment by anton-karlovskiy** [comment]
@addyosmani 

Currently in the hooks if the API is not supported, we return some UNSUPPORT_MESSAGE but I think it might be confusing to check whether a hook is available or not based on API availability in the background.

So I think we can just return null if the API is not supported and based on if the hook value is null or not, we can show corresponding UNSUPPORT MESSAGE or some exception handling in the projects.

Could you please give me your thought on this?

**Comment by addyosmani** [comment]
Could you show me a quick code snippet on here (something short) that demonstrates how you see a developer handling null being returned with one hook? I think this makes sense and is in line with how you would handle this if just using vanilla JS.

**Comment by anton-karlovskiy** [comment]
@addyosmani 

```
import React from 'react';

import { useSaveData } from './save-data';

const MyComponent = () => {
  const { saveData } = useSaveData();

  If (saveData === null) {
    console.log('[MyComponent] saveData is not available.');
    return <video src='...' />;
  }

  return (
    <div>
      { saveData ? <img src='...' /> : <video src='...' /> }
    </div>
  );
};
```

Please review the above code snippet.

**Comment by anton-karlovskiy** [comment]
@addyosmani 

As for using vanilla JS, could you please explain a bit more? I think I have not got it.

**Comment by addyosmani** [comment]
The above was enough to explain it. Thanks!

**Comment by anton-karlovskiy** [comment]
Sub tasks:
- updating hooks and their Unit Tests
- updating corresponding demos
- local testing and re-deployment and online testing
- updating hooks README

**Comment by anton-karlovskiy** [comment]
@addyosmani 
I think we should figure out the way in which we can reference the hooks from the main project not copying and pasting them inside individual projects.
I think we can save potential efforts in future updates. Shall we open an issue for this?

**Comment by addyosmani** [comment]
How about I publish the hooks package to npm and we reference that via package.json vs copying/pasting? Would that work?

**Comment by anton-karlovskiy** [comment]
@addyosmani 
I think that should work. According to stackoverflow articles, that was one solution.
