### ISSUE TITLE
[Demo] Enhance Twitter Data Saver demo

### ISSUE THREAD

**Issue by addyosmani** [GoogleChromeLabs/adaptive-loading#83]
I believe our Twitter Data Saver demo also included support for embedded videos in Tweets: https://github.com/GoogleChromeLabs/adaptive-loading/blob/master/react-twitter-save-data-loading(hook)/src/components/Tweet/Video.js

If we have time, I would like for us to enhance the current Hooks demo so that the 4th sample tweet is https://twitter.com/mrdoob/status/1131817655134896128. This would allow us to demonstrate what a LQIP/blurred image for a video entry would look like (just an image) when data saver is on and we can then load the video on tap the way Twitter's current experience works.

The video for this tweet is attached 📦

[main-video2.mp4.zip](https://github.com/GoogleChromeLabs/adaptive-loading/files/3790091/main-video2.mp4.zip)

cc @anton-karlovskiy

**Comment by anton-karlovskiy** [comment]
@addyosmani 

I've updated the client hint version accordingly since I thought it would take 20 minutes or so.
https://adaptive-loading.web.app/react-twitter-save-data-loading(client-hint)

**Comment by anton-karlovskiy** [comment]
@addyosmani 

FYI: I think the codebase is a bit messy as I just adopted [react-tweet project](https://github.com/mannynotfound/react-tweet) and did not refactor it because I thought it would take quite some time to refactor adequately.

**Comment by addyosmani** [comment]
No worries. Given this is a demo, I think that is okay. Could we update the tweet text, avatar and username for that entry to match the tweet I linked to as well? Would it be hard to also add this change to the hooks demo?

**Comment by anton-karlovskiy** [comment]
> No worries. Given this is a demo, I think that is okay. Could we update the tweet text, avatar and username for that entry to match the tweet I linked to as well? Would it be hard to also add this change to the hooks demo?

I think it's not so difficult. After adding, we might have to adjust the view on desktop and mobile.

**Comment by anton-karlovskiy** [comment]
@addyosmani 

The look and feel of the video tweet is updated with copy of the original appearance.
Please review this.
![Capture](https://user-images.githubusercontent.com/49653735/68546636-975ded80-03e9-11ea-9c20-d2e5c5a5f00d.PNG)

**Comment by anton-karlovskiy** [comment]
@addyosmani 

Looks like this project does not quite fit for mobile responsive view, although I tweaked a bit in the past.
This is also mentioned in [TODO: of the orignal project](https://github.com/mannynotfound/react-tweet).

I've checked that it's okay on Sumsung Galaxy 9.

**Comment by addyosmani** [comment]
This looks perfect, Anton! Thank you!
