### ISSUE TITLE
[Demos] Polish

### ISSUE THREAD

**Issue by addyosmani** [GoogleChromeLabs/adaptive-loading#86]
While going through the demos, I had some minor feedback on tweaks we could make :)

### Move text at the top of the demo to the very bottom

* https://adaptive-loading.web.app/node-network-memory-considerate-loading/
* https://adaptive-loading.web.app/node-network-aware-loading/
* https://adaptive-loading.web.app/node-memory-considerate-loading/
* https://adaptive-loading.web.app/node-dpr-aware-loading/
* https://adaptive-loading.web.app/cra-device-class-aware-loading/ 
* https://cna-memory-animation.firebaseapp.com/ (but keep the toggle where it is right now)
* https://adaptive-loading.web.app/cra-memory-considerate-loading-sketchfab/
* https://adaptive-loading.web.app/cra-memory-considerate-loading/

### Other

* https://adaptive-loading.web.app/cra-network-aware-code-splitting/ I have resized and compressed the 1.2MB image [here](https://user-images.githubusercontent.com/110953/68065791-50863e80-fceb-11e9-99e2-37620b11324a.jpg). Could we use this version and localize it for the demo?

cc @anton-karlovskiy

**Comment by anton-karlovskiy** [comment]
@addyosmani 

Yes, I got everything.
FYI: currently we are using .webp images in some demos. Is it okay?

**Comment by anton-karlovskiy** [comment]
@addyosmani 

I'd like to suggest that we should rename `cra-device-class-aware-loading` to `cra-device-class-aware-code-splitting` in this task.
I keep it mind that we will be updating the name scheme.

**Comment by anton-karlovskiy** [comment]
@addyosmani 

![Capture](https://user-images.githubusercontent.com/49653735/68082048-b5937e80-fe28-11e9-9f51-be9ba710fb56.PNG)
We have the warnings in some demos with online URL. Should we fix this?

**Comment by addyosmani** [comment]
I think it's okay for the SketchFab models to still load from third party
sites with those warnings and I'm also okay on WebP. Do you know which
demos rely on it at tge moment?

We could use the picture tag to provide a fallback. On renaming: that
sounds fine

**Comment by anton-karlovskiy** [comment]
@addyosmani 

`react-dixie-memory-considerate-loading`, `react-ebay-network-aware-code-splitting` demos rely on webp images.

**Comment by anton-karlovskiy** [comment]
@addyosmani 

I double checked updated demos on firebase hosting. Looks like they are working as expected.

**Comment by addyosmani** [comment]
👍
