### ISSUE TITLE
[Demos] YouTube 

### ISSUE THREAD

**Issue by addyosmani** [GoogleChromeLabs/adaptive-loading#87]
Description:

There's a neat [YouTube demo](https://github.com/marvtron/youtube-react) implemented using React which allows you to see the homepage of videos, the watch page and search page. 

I would like for us to make it a little smarter by:

📹 [P0] Video watch page: instead of loading the full [embed-video component](https://github.com/marvtron/youtube-react/blob/cbb1a2fffd61d2313ebeefcd3ca4936b3b21e516/youtube-react/src/components/Video/Video.js), we: check if you are on a slow network OR a low-memory device OR have low hardware concurrency and serve down a [lighter](https://glitch.com/~lite-youtube-embed) custom element for the player instead (we may need to wrap it a little for use in React). We can use a similar pattern to network aware code-splitting, but add checks for memory and concurrency in the same boolean check within `React.lazy()`. 

 🔗 [P0] Routing: Fix routing so that the links to https://marvtron.github.io/watch?v=GKXS_YA9s7E (etc) take you to https://marvtron.github.io/youtube-react/watch?v=GKXS_YA9s7E. Accessing https://marvtron.github.io/youtube-react/watch?v=GKXS_YA9s7E directly should load the video watch page.

🙊 [P1] On slow network or low-memory or low hardware-concurrency, don't load the comments widget and limit (by half) the number of results returned for the recommended videos:

![image](https://user-images.githubusercontent.com/110953/68074142-2bc6b100-fd55-11e9-9df5-0dae826cb9eb.png)

🔧 [P0] I would like us to add the following code to the index so we can quickly show on the watch page which components are important vs not.

```js
<script>
window.debug = () => {
   document.querySelector('.video-container').style.border = '15px solid green';
   document.querySelector('.related-videos').style.border = '15px solid red';
   document.querySelector("#root > div > div.watch-grid > div:nth-child(5)").style.border = '15px solid red';
};
</script>
```

🎨[P2] Take a quick look at whether render-blocking CSS can be optimized (e.g do we need all of semantic-ui?). I was reading through https://marvtron.github.io/youtube-react/static/css/2.20edb33d.chunk.css and at the very least, I think we don't need to load in the import for the Lato font. YouTube just uses Roboto if installed and I'm cool with us falling back to Arial without loading a Web Font (`font-family: roboto, arial, sans-serif; `)

I would say this is probably higher priority than #https://github.com/GoogleChromeLabs/adaptive-loading/issues/63 for this week but could be looked at after #86 (#86, #87, #83, then #63).  

cc @anton-karlovskiy

**Comment by anton-karlovskiy** [comment]
@addyosmani 

It's a bit urgent.
I have been working on [P0] (adaptive video player component).
Suddenly https://marvtron.github.io/youtube-react/ is not working.

**Comment by anton-karlovskiy** [comment]
@addyosmani 

![Capture](https://user-images.githubusercontent.com/49653735/68135303-7ce0cb80-ff34-11e9-99d7-280044e2e2c2.PNG)

The message is like the following:
`Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube.googleapis.com/quotas?project=7956948267`

**Comment by anton-karlovskiy** [comment]
@addyosmani 

Regarding `[P0] Video watch page: instead of loading the full embed-video component, we: check if you are on a slow network OR a low-memory device OR have low hardware concurrency and serve down a lighter custom element for the player instead (we may need to wrap it a little for use in React). We can use a similar pattern to network aware code-splitting, but add checks for memory and concurrency in the same boolean check within React.lazy().`

Should we not use hooks for memory and concurrency?
If we use hooks, we might not be able to use network aware code-splitting pattern because I think hooks are not available in `React.lazy() async method`. So I'd like to suggest that we could use network hook, memory hook, concurrency hook.

**Comment by addyosmani** [comment]
Ultimately, I want us to use whichever option (hooks or the direct APIs) allows us to avoid sending down the extra code to users. It sounds like we should use hooks and can circle back if we need to rethink this.

If I remember correctly, using the hooks allows us to decide whether to **show** a heavy or light component but doesn't let us change what bundle gets **loaded**. Is that correct? We may be okay to use the hooks given the change is "are we using YouTube's iframe embed, that loads in a bunch of its own scripts vs using our own custom lazy-loading embedder?".

**Comment by anton-karlovskiy** [comment]
@addyosmani 

Thank you for your clarifying.
I've got your points. As for bundle loading by hooks, I think I should experiment once more as I thought it allows us to change what bundle gets loaded by webpack default configuration of create-react-app.
We can check it soon. I'm wrapping up this feature.

**Comment by addyosmani** [comment]
Awesome. Thanks, Anton!

**Comment by anton-karlovskiy** [comment]
@addyosmani 

I think we've reached the quota limit again.
Could you please check it? Can we increase the quota because we should keep requesting in the process of development?
https://console.cloud.google.com/apis/api/youtube.googleapis.com/quotas?folder=&organizationId=&project=adaptive-loading&duration=P30D

**Comment by anton-karlovskiy** [comment]
@addyosmani 

I've checked the bundle chunks for both lite and heavy mode.
![heavy](https://user-images.githubusercontent.com/49653735/68226807-be8c7780-0003-11ea-9046-c3a11024f5e4.PNG)
![lite](https://user-images.githubusercontent.com/49653735/68226808-be8c7780-0003-11ea-8aa0-819189f80ffd.PNG)

In my opinion, using hooks not only allows us to decide wether to show a heavy or light component but also let us control what bundle gets loaded according to the [current deployed project](https://adaptive-loading.web.app/react-youtube/).
So I think there is no significant difference in chunks loading if we just use hooks other than network code-splitting pattern.

Could you please confirm if this is correct?

**Comment by addyosmani** [comment]
That matches my thinking too. Let's move ahead using Hooks here... :)

**Comment by anton-karlovskiy** [comment]
@addyosmani 

Because [user changing the `data-videoid` attribute](https://github.com/paulirish/lite-youtube-embed/blob/77b70e2279db13ee39aac3d021073687d53c6811/index.html#L152) is not supported, dynamically setting the attribute is not working yet.
For example, just clicking on a video in the list does not properly open a video.

![Capture](https://user-images.githubusercontent.com/49653735/68262581-bad51100-0054-11ea-9043-5eb1e3800996.PNG)

**Comment by addyosmani** [comment]
Ah, I see. This makes sense. Given we won't be clicking on links in the
sidebar I think this is OK.

**Comment by anton-karlovskiy** [comment]
@addyosmani 
> [P0] I would like us to add the following code to the index so we can quickly show on the watch page which components are important vs not.

**Comment by addyosmani** [comment]
After taking a look at the latest commits, we could get by without working on the P2 (for now - unless you've started an implementation already?). 

The demo as-is is pretty solid. With respect to the window.debug() issue we are running into, my current workflow is to paste the code for this into the DevTools console and just run it. Given this, I don't think it's worth us spending too much time looking at why this wasn't working.

**Comment by anton-karlovskiy** [comment]
@addyosmani 

Yes, as we discussed about that alternative with respect to `window.debug()`, I have not spent much time fixing it.
For P2 as well, I thought it was what we could circle back.

**Comment by anton-karlovskiy** [comment]
@addyosmani 

https://github.com/GoogleChromeLabs/adaptive-loading/issues/87#issuecomment-551517621

FYI: Currently it's working for the version deployed on Firebase.
![Capture](https://user-images.githubusercontent.com/49653735/68918094-dd1a0d80-077d-11ea-9f81-af8a32558be6.PNG)

**Comment by anton-karlovskiy** [comment]
@addyosmani 

We just have [P2]. Shall I add this to the backlog and handle this?

**Comment by addyosmani** [comment]
I think it's okay to skip the P2. Perhaps now is a good time to switch to the migration over to the react-adaptive-hooks project while waiting on extra microsite feedback?

**Comment by anton-karlovskiy** [comment]
@addyosmani 

This project is missing from the README of https://github.com/GoogleChromeLabs/react-adaptive-hooks.
Is this on purpose?

**Comment by anton-karlovskiy** [comment]
> I think it's okay to skip the P2. Perhaps now is a good time to switch to the migration over to the react-adaptive-hooks project while waiting on extra microsite feedback?

It's started. Right now I'm working on updating demos based on `react-adaptive-hooks` package.

**Comment by addyosmani** [comment]
Missing: nope not on purpose!

**Comment by addyosmani** [comment]
@anton-karlovskiy Would you like to file a PR against the hooks project to add the YouTube app to the list of demos?

**Comment by anton-karlovskiy** [comment]
@addyosmani 

No problem. Let me handle.
