### ISSUE TITLE
[Config] Implement API key safety restrictions

### ISSUE THREAD

**Issue by addyosmani** [GoogleChromeLabs/adaptive-loading#91]
A minority of our demos leverage live data from a third-party API. We should avoid storing API keys directly in the source as this is against Google best practices. We should fix this after Chrome Dev Summit.

> Do not embed API keys directly in code. API keys that are embedded in code can be accidentally exposed to the public. For example, you may forget to remove the keys from code that you share. Instead of embedding your API keys in your applications, store them in environment variables or in files outside of your application's source tree.

The best practice here is to leverage [application and API key restrictions](https://cloud.google.com/docs/authentication/api-keys#api_key_restrictions). By adding restrictions, we can reduce the impact of a compromised API key and can set what referrers or IPs can use the key:

![image](https://user-images.githubusercontent.com/110953/68521918-93e82c00-025a-11ea-8f9a-f8d2fa78f52c.png)

**Comment by anton-karlovskiy** [comment]
@addyosmani 

It's configured like the following.
![api-restrictions](https://user-images.githubusercontent.com/49653735/68714297-ae9b0780-05b0-11ea-9612-ac1e75fb7cdc.PNG)
