### ISSUE TITLE
[Update] Updating the adaptive-loading demos to use the new package of hooks

### ISSUE THREAD

**Issue by anton-karlovskiy** [GoogleChromeLabs/adaptive-loading#93]
A new task high up in priority is a PR that updates the adaptive-loading demos to use the new package of hooks from npm (where possible)

**Comment by anton-karlovskiy** [comment]
@addyosmani 

I think battery hook is missing from `react-adaptive-hooks`. Is it on purpose?

**Comment by addyosmani** [comment]
Yeah, we dropped it as Battery Status API is likely going away. I think we can continue using a custom hook in this repo for it during the time being.
