### ISSUE TITLE
[Microsite] Resources page

### ISSUE THREAD

**Issue by addyosmani** [GoogleChromeLabs/adaptive-loading#97]
URL: https://anton-karlovskiy-adaptive-loading-microsite.glitch.me/resources

Can we take the existing browser compatibility and references sections from https://github.com/GoogleChromeLabs/react-adaptive-hooks/blob/master/README.md and incorporate them into the resources section? 

We can also link up to the recent write-up from Instagram about how they are using adaptive loading: https://medium.com/@roderickhsiao/sophisticated-adaptive-loading-strategies-7118341fcf91

cc @anton-karlovskiy

**Comment by addyosmani** [comment]
If we can also drop the search icon from the navigation that would be ace.

**Comment by anton-karlovskiy** [comment]
@addyosmani 

Should we remove `Browser Support` and `References` sections from `react-hooks` page as we have them in the `resources` page?

**Comment by addyosmani** [comment]
I think this sounds good
