### ISSUE TITLE
[Microsite] Deployment

### ISSUE THREAD

**Issue by addyosmani** [GoogleChromeLabs/adaptive-loading#98]
As the microsite project is coming along well so far, I would like for us to explore deploying it to http://adaptive-loading.web.app/ as the root/main page on the domain. This would allow us to get a better idea of how the implementation performs on production and consider if any further performance optimizations are needed on the server-side.

cc @anton-karlovskiy

**Comment by anton-karlovskiy** [comment]
@addyosmani 

To deploy the Microsite project as the root page, I'm going to move the project repository into the adaptive loading demos project repository.

Does it sound good?

**Comment by addyosmani** [comment]
Yes, this sounds good to me. Thanks!

**Comment by anton-karlovskiy** [comment]
@addyosmani 

https://adaptive-loading.web.app/
It's up and running at the root page.

**Comment by anton-karlovskiy** [comment]
@addyosmani 

I think we can close this issue.
We've implemented even SSR cache.

**Comment by addyosmani** [comment]
This sounds great to me. Thank you for working on the latest revisions. The site is looking great.
